
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/garyburd/redigo"

[[constraint]]
  name = "github.com/goware/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/goware/urlx"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/goamz"

[[constraint]]
  branch = "v2"
  name = "github.com/pressly/chainstore"

[[constraint]]
  name = "github.com/pressly/chi"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/pressly/consistentrd"

[[constraint]]
  name = "github.com/pressly/lg"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/tobi/airbrake-go"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/render"

[[constraint]]
  name = "github.com/zenazn/goji"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/gographics/imagick.v3"
  version = "3.2.0"
